# blank_lines_lower_bound = true # released version (1.4.36) awful, version on master great
# chain_width = 100 # enable on release
edition = "2018"
enum_discrim_align_threshold = 4 # unstable
# fn_call_width = 100 # enable on release
force_multiline_blocks = true # unstable
format_code_in_doc_comments = true # unstable
group_imports = "StdExternalCrate" # unstable
imports_granularity = "Module"
match_block_trailing_comma = true
max_width = 120
merge_derives = true
newline_style = "Auto"
normalize_doc_attributes = true # unstable
# preserve_closure_block_wrapping = true # actually nice, but of questionable stability
remove_nested_parens = true
reorder_impl_items = true # unstable
# single_line_if_else_max_width = 100 # enable on release
# struct_lit_width = 70 # enable on release
# struct_variant_width = 70 # enable on release
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
